# **Identitas**

Nama : **Iftitah Hidayati**

Kelas : TI 3H

NIM : 2041720006

No. Presensi : 11

# **Principal Component Analysis Secara Manual**

In [2]:
from numpy import array
from numpy import mean
from numpy import cov
from numpy.linalg import eig
# define a matrix
A = array([[1, 2], [3, 4], [5, 6]])
print(A)
print('==================================================')
# calculate the mean of each column
M = mean(A.T, axis=1)
print(M)
print('==================================================')
# center columns by subtracting column means
C = A - M
print(C)
print('==================================================')
# calculate covariance matrix of centered matrix
V = cov(C.T)
print(V)
print('==================================================')
# eigendecomposition of covariance matrix
values, vectors = eig(V)
print(vectors)
print('==================================================')
print(values)
print('==================================================')
# project data
P = vectors.T.dot(C.T)
print(P.T)

[[1 2]
 [3 4]
 [5 6]]
[3. 4.]
[[-2. -2.]
 [ 0.  0.]
 [ 2.  2.]]
[[4. 4.]
 [4. 4.]]
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]
[8. 0.]
[[-2.82842712  0.        ]
 [ 0.          0.        ]
 [ 2.82842712  0.        ]]


# **Principal Component Analysis Menggunakan SKlearn**

In [3]:
# Principal Component Analysis Menggunakan SKlearn
from numpy import array
from sklearn.decomposition import PCA
# define a matrix
A = array([[1, 2], [3, 4], [5, 6]])
print(A)
# create the PCA instance
pca = PCA(2)
# fit on data
pca.fit(A)
# access values and vactors
print(pca.components_)
print(pca.explained_variance_)
# transform data
B = pca.transform(A)
print(B)

[[1 2]
 [3 4]
 [5 6]]
[[ 0.70710678  0.70710678]
 [-0.70710678  0.70710678]]
[8. 0.]
[[-2.82842712e+00 -2.22044605e-16]
 [ 0.00000000e+00  0.00000000e+00]
 [ 2.82842712e+00  2.22044605e-16]]


# **Principal Component Analysis Menggunakan SKlearn diterapkan pada data heart-disease**

In [6]:
import pandas as pd
import io

from google.colab import files
upload=files.upload()

Saving heart.csv to heart.csv


In [17]:
# import pandas as pd
# patients_data = pd.read.csv(io.BytesIO(upload['heart.cvs']

import numpy as np
import pandas as pd

patients_data = pd.read_csv('/content/drive/MyDrive/Data/PembelajaranMesin/P15/heart.csv')
patients_data.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [18]:
from sklearn.model_selection import train_test_split # Import train_test_split fuction
import numpy as np
import matplotlib.pyplot as plt
from pandas.plotting import scatter_matrix

patients_data_train, patients_data_test = train_test_split(patients_data, random_state= 42, test_size=0.30, stratify=patients_data['target'])
X_train = patients_data_train.drop('target', axis=1)
y_train = patients_data_train['target']
X_test = patients_data_test.drop('target', axis=1)
y_test = patients_data_test['target']

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test=scaler.fit_transform(X_test)


In [21]:
from sklearn.decomposition import PCA
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier # Import Decision Tree Classifier

pca = PCA().fit(X_train)
pca = PCA(n_components=5)
X_reduced_train = pd.DataFrame(pca.fit_transform(X_train))
X_reduced_test = pd.DataFrame(pca.fit_transform(X_test))

knn = KNeighborsClassifier(n_neighbors=14)
knnPCA =knn.fit(X_reduced_train, y_train)
print("Train set score using KNN as classifier:{:.2f}".format(knn.score(X_reduced_train, y_train)))
print("Test set score using KNN as classifier:{:.2f}".format(knn.score(X_reduced_test, y_test)))

knnNon = knn.fit(X_train,y_train)
y_pred = knn.predict(X_test)
print("Test set score using knn non PCA as classifier: {:.2f}".format(knn.score(X_test, y_test)))

clf = DecisionTreeClassifier()
heart_disease_DT = clf.fit(X_reduced_train, y_train)
print("Train set score using CART as classifier:{:.2f}".format(clf.score(X_reduced_train, y_train)))
print("Test set score using CART as classifier:{:.2f}".format(clf.score(X_reduced_test, y_test)))

clfNon = clf.fit(X_train, y_train)
print("Test set score using CART non PCA as classifier: {:.2f}".format(clf.score(X_test, y_test)))

Train set score using KNN as classifier:0.85
Test set score using KNN as classifier:0.81
Test set score using knn non PCA as classifier: 0.80
Train set score using CART as classifier:1.00
Test set score using CART as classifier:0.81
Test set score using CART non PCA as classifier: 0.69
